name: Releasing APK files
runs:
  using: "composite"
  steps:
    - name: Release
      uses: ncipollo/release-action@v1.21.0
      with:
        artifacts: |
          ./release/*.apk
        name: NexAlloy-NonRoot
        tag: all
        body: "You must remove both Messenger and Facebook, then install this build"
        allowUpdates: true
